---
- name: Apply the HTC Gitian builder role.
  become: yes
  hosts: localhost:htc-build
  vars:
    htc_git_repo_url: https://github.com/smupyknight/htc.git
    htc_version: v1.0.0
    gpg_key_name: 'smupyknight'
    git_name: 'smupyknight'
    git_email: 'smupyknight@outlook.com'
    gpg_key_id: '668F534AB86DC7704DFB62830B56009F12D3A453' # optional
    ssh_key_name: 'id_rsa' # optional
  roles:
    - role: common
      tags: common
    - role: gitian
      tags: gitian
