---
htc_swapfile_size: 1G
htc_vm_swappiness: 1
htc_common_packages:
  - apt-show-versions
  - apt-transport-https
  - curl
  - git-core
  - haveged
  - htop
  - ntp
  - ntpdate
  - python-pip
  - rsync
  - screen
  - sudo
  - tmux
  - tree
  - vim
