---
galaxy_info:
  author: Smupyknight (@smupyknight)
  description: Sets up a deterministic Gitian builder VM for HTC.
  company: HTC
  galaxy_tags: []
  license: GPLv2
  min_ansible_version: 2.1.2
  platforms:
    - name: Debian
      versions:
      - jessie
  categories:
    - system
dependencies: []
